### ISSUE TITLE
Inline fragment indentation

### ISSUE THREAD

**Issue by sj26** [jparise/vim-graphql#5]
Thanks for the plugin!

I noticed that inline fragments indent like this when anything but the first field:

```graphql
query {
  field
    ...on SomeType {
      anotherField
    }
}
```

Also `on` in `...on SomeType` doesn't highlight as a keyword.

**Comment by jparise** [comment]
1d21bed should fix the syntax highlighting problem.

I'll move on to the indent issue once I get another block of time because I suspect it will require a more involved solution.

**Comment by jparise** [comment]
I believe your indenting issue is caused by having `cindent` enabled. If you disable it, I think you'll find that indentation works as you'd expect.

Given that, I'm inclined to have this plugin set `nocindent` on GraphQL buffers. `smartindex` / `autoindent` should be sufficient for the grammar, but if we find additional cases where they aren't, we can go as far as defining a GraphQL-specific `indentexpr`.
