### ISSUE TITLE
Submit to vim/vim

### ISSUE THREAD

**Issue by ryu-ichiroh** [jparise/vim-graphql#94]
Hi jparise.

Do you want to try to add to [vim/vim](https://github.com/vim/vim)?

`jparise/vim-graphql` is the most popular plugin for GraphQL.
https://github.com/search?o=desc&q=vim+graphql&s=stars&type=Repositories

Now vim/vim is not support graphql, not even syntax highlighting.
https://github.com/vim/vim/tree/master/runtime/syntax

Of course the rights keep yours.

The following links are a case of `rust-lang/rust.vim`.

* https://github.com/vim/vim/issues/1354
* https://github.com/rust-lang/rust.vim/issues/134
* https://github.com/vim/vim/pull/1356

Thanks.

**Comment by jparise** [comment]
That's an interesting idea, @ryu-ichiroh, and not one that I had previously considered.

One potential downside: vim-graphql currently integrates with a few other projects for improved syntax highlighting, such as https://github.com/pangloss/vim-javascript. I think we'd need to give that up if the code was part of vim itself. It might not be a big loss overall, but it's a consideration.

We would also need to rewrite the current test suite in terms of vim's own test assertions rather than [Vader](https://github.com/junegunn/vader.vim). That could be a good project to do in general, although it's not a priority.

**Comment by ryicoh** [comment]
@jparise Thank you for your positive comment!

As for the integrations and testing, [vim/vim ](https://github.com/vim/vim) would not need them and It's enough to import `ftplugin/`, `idnent/`, and `syntax/`.
(I understand that the integration is a great feature and testing make the project keep to reduce errors.)

I made a patch to make it easier for you to submit. https://github.com/ryu-ichiroh/vim/pull/1/files

Most of the code was taken over from `vim-graphql`, and modified the headers as brammool's comment.
https://github.com/vim/vim/pull/1356#issuecomment-270978696

**Comment by ryu-ichiroh** [comment]
@jparise Thank you for your positive comment!

As for the integrations and testing, [vim/vim ](https://github.com/vim/vim) would not need them and It's enough to import `ftplugin/`, `idnent/`, and `syntax/`.
(I understand that the integration is a great feature and testing make the project keep to reduce errors.)

I made a patch to make it easier for you to submit. https://github.com/ryu-ichiroh/vim/pull/1/files

Most of the code was taken over from `vim-graphql`, and modified the headers as brammool's comment.
https://github.com/vim/vim/pull/1356#issuecomment-270978696

**Comment by jparise** [comment]
Thanks, @ryu-ichiroh! I need to give this a little more thought to form a better understanding of what I'm actually signing up to maintain (🙂), but it does seem like a good idea.

**Comment by jparise** [comment]
I'm (slowly) making preparations to contribute some or all of this work to upstream vim. #108 is a recent example that standardizes the scripts based on vim's conventions.

**Comment by jparise** [comment]
Initial vim contribution: https://github.com/vim/vim/pull/16273
